name: PortalGun
main: com.rogermiranda1000.portalgun.PortalGun
version: "${project.version}"
author: rogermiranda1000
description: Plugin inspired in the PortalGun from Portal.
api-version: 1.13
softdepend: [Gson-for-1-7-10,Multiverse-Core,Residence,WorldGuard]
commands:
    portalgun:
        description: Get the PortalGun
        usage: /<command>
permissions:
    portalgun.portalgun:
        description: Get the PortalGun
        default: op
    portalgun.open:
        description: Open portals
        default: true
    portalgun.entities:
        description: Take entities
        default: true
    portalgun.remove:
        description: Remove your portals
        default: true
    portalgun.destroy:
        description: Can destroy portals placing or breaking blocks.
        default: true
    portalgun.emancipator:
        description: Get the emancipation block
        default: op
    portalgun.companion:
        description: Spawn a companion block
        default: op
    portalgun.remove.others:
        description: Remove others' portals
        default: op
    portalgun.remove.all:
        description: Remove all the portals
        default: op
    portalgun.overrideblocks:
        description: Override only in certain blocks condition
        default: op
    portalgun.overrideotherportals:
        description: Override 'only your portals' condition
        default: op
    portalgun.boots:
        description: Get the Portal Boots
        default: true
    portalgun.report:
        description: Send reports
        default: op